### ISSUE TITLE
8.1 - PROTÓTIPO TELA DE SENSORES (FRONT)

### ISSUE THREAD

**Issue by bruno-pisciotta281** [Conveccao/conveccao-frontend#1]
Construir um prototipo navegável da tela de cadastro de sensores.

**Peso:** 3

**Prioridade:** ALTA

**DoD**

**[  ]** PROTÓTIPO NAVEGÁVEL DA TELA DE DASHBOARD, PARA ENTENDIMENTO MAIOR DO PRODUTO

**Comment by drisabelles** [comment]
[X] PROTÓTIPO NAVEGÁVEL DA TELA DE DASHBOARD, PARA ENTENDIMENTO MAIOR DO PRODUTO
