### ISSUE TITLE
9.1 - TELA DE LOGIN (FRONT)

### ISSUE THREAD

**Issue by bruno-pisciotta281** [Conveccao/conveccao-frontend#11]
Tela onde os usuários se conectarão na plataforma.

Prioridade: ALTA

DoD: Tela precisa dar acesso a plataforma pelas redes sociais Facebook e Google, ter a parte de cadastro de usuários caso o usuário não tenha conta.

**Comment by vbuarque** [comment]
Data de inicio da task: 23/09

**Comment by vbuarque** [comment]
23/09
Horas trabalhadas:
2h

(até o final do dia ainda irei trabalhar na mesma task)

**Comment by vbuarque** [comment]
27/09
Horas trabalhadas: 1h

**Comment by vbuarque** [comment]
Task finalizada, enviada para review
