### ISSUE TITLE
6.1 - PÁGINA INÍCIAL (FRONT) -

### ISSUE THREAD

**Issue by bruno-pisciotta281** [Conveccao/conveccao-frontend#14]
# PÁGINA INÍCIAL 

## **Definition of Ready:**

**Descrição:** Página de dashboard contendo mapa com as estações cadastradas, principais estações, menu lateral e superior.(SEGUIR DE ACORDO COM O WIREFRAME)  

**PRIORIDADE DO ITEM:** ALTA

**USER STORY:** 0

**PESO:** 5

**REQUISITO:** FUNCIONAL

## **Definition of Done:** 

**CHECKLIST DE ITENS :**

- [ ] MAPA MOSTRANDO AS ESTAÇÕES QUE FOREM CADASTRADAS
- [ ] LOCAL MOSTRANDO AS PRINCIPAIS ESTAÇÕES(estações mais antigas)

- [ ] MENU LATERAL COM OS ITENS (PÁGINA INICIAL E PERFIL) - USUARIOS NORMAIS
- [ ] MENU LATERAL COM OS ITENS (PÁGINA INICIAL, PERFIL, USUÁRIOS CADASTRADOS, CADASTRO DE ESTAÇÕES E ESTAÇÕES CADASTRADAS) - USUARIOS ADM.

- [ ] CASO USUÁRIO ESTEJA LOGADO BOTÃO SAIR
- [ ] CASO USUÁRIO NÃO ESTEJA LOGADO, BOTÃO ENTRAR 

- [ ] 100% IGUAL AO WIREFRAME

### ** STATUS: EM ANDAMENTO **

**Comment by vbuarque** [comment]
Feature finish 08/10
