### ISSUE TITLE
6.2 - MAPA COM ESTAÇÕES (FRONT)

### ISSUE THREAD

**Issue by bruno-pisciotta281** [Conveccao/conveccao-frontend#15]
# MAPA COM ESTAÇÕES

## **Definition of Ready:**

**Descrição:** Mapa com as estações cadastradas, sendo possível ver os dados quando clica em cima de cada estação.
(SEGUIR DE ACORDO COM O WIREFRAME)  

**PRIORIDADE DO ITEM:** ALTA

**USER STORY:** 2

**PESO:** 

**REQUISITO:** FUNCIONAL

## **Definition of Done:** 

**CHECKLIST DE ITENS :**

- [ ] MAPA CONTENDO AS ESTAÇÕES QUE FOREM SENDO CADASTRADAS.
- [ ] CADA ESTAÇÃO NO MAPA TEM QUE SER CLICÁVEL E LEVANDO PARA A PAGINA DA ESTAÇÃO A QUAL FOI CLICADA.
- [ ] COMANDOS DE MANUSEIO DO MAPA(ZOOM E MEXER COM O MOUSE UTILIZANDO-SE DO MOVIMENTO DE ARRASTAR).

**Comment by vbuarque** [comment]
Feature finish 08/10
