### ISSUE TITLE
7.1 - PROTÓTIPO TELA DE ESTAÇÕES (FRONT)

### ISSUE THREAD

**Issue by bruno-pisciotta281** [Conveccao/conveccao-frontend#2]
Construir um prototipo navegável da tela de cadastro de estações.

**Peso:** 3

**Prioridade:** ALTA 

**DoD**

**[  ]** PROTÓTIPO NAVEGÁVEL DA TELA DE ESTAÇÃO, PARA ENTENDIMENTO MAIOR DO PRODUTO

**Comment by drisabelles** [comment]
[X] PROTÓTIPO NAVEGÁVEL DA TELA DE ESTAÇÃO, PARA ENTENDIMENTO MAIOR DO PRODUTO
