### ISSUE TITLE
6.1 - PROTÓTIPO TELA DE DASHBOARD (FRONT)

### ISSUE THREAD

**Issue by bruno-pisciotta281** [Conveccao/conveccao-frontend#3]
Construir o protótipo navegável da tela de dashboard, onde os usuário irão poder visualizar os dados metereológicos.

**Peso:** 3

**Prioridade:** ALTA

**DoD**

**[  ]** PROTÓTIPO NAVEGÁVEL DA TELA DE DASHBOARD, PARA ENTENDIMENTO MAIOR DO PRODUTO

**Comment by drisabelles** [comment]
[X] PROTÓTIPO NAVEGÁVEL DA TELA DE DASHBOARD, PARA ENTENDIMENTO MAIOR DO PRODUTO
