### ISSUE TITLE
7.2 - CRIAÇÃO TELA DE ESTAÇÕES (FRONT)

### ISSUE THREAD

**Issue by bruno-pisciotta281** [Conveccao/conveccao-frontend#5]
Criação da tela de estações para o cadastramento de estações

**Peso:** 5

**Prioridade:** Alta

**DoD**

**[  ]** Formulário de cadastro solicitando informações para cadastro
**[  ]** Estrutura de acordo com o protótipo navegável

**Comment by drisabelles** [comment]
Commitadas as alterações e criações da tela respectiva ao registro de estações

**Comment by drisabelles** [comment]
[X] Formulário de cadastro solicitando informações para cadastro
[X] Estrutura de acordo com o protótipo navegável
