### ISSUE TITLE
8.2 - CRIAÇÃO DE TELA SENSORES (FRONT)

### ISSUE THREAD

**Issue by bruno-pisciotta281** [Conveccao/conveccao-frontend#6]
Criação da tela de sensores para a visualização dos dados.

**Peso:** 5

**Prioridade:** ALTA

**DoD**

**[  ]** Formulário de cadastro solicitando informações para cadastro
**[  ]** Estrutura de acordo com o protótipo navegável

**Comment by drisabelles** [comment]
[X] Formulário de cadastro solicitando informações para cadastro
[X] Estrutura de acordo com o protótipo navegável
