### ISSUE TITLE
6.2 - CRIAÇÃO TELA DE DASHBOARD (FRONT)

### ISSUE THREAD

**Issue by bruno-pisciotta281** [Conveccao/conveccao-frontend#8]
Criação da tela de dashboard para a visualização dos dados.

Peso: 5

Prioridade: ALTA

DoD

[x] Página de bem vindo (futura página de login)
[x] Gráficos e Tabelas informando alguns dados (mockados)
[x] Modo de visualização de dados funcionais
[x] Acesso a botão para a página de cadastro de estações
[x] Acesso a botão para a página de cadastro de sensores

**Comment by vbuarque** [comment]
Iniciando dia 13/09 - Horas trabalhadas: (ainda a ser atualizado)

**Comment by vbuarque** [comment]
Finalizando dia 16/09 - Horas trabalhadas: 8 horas no total

13/09 - 2
14/09 - 2
15/09 - 2
16/09 - 2

**Comment by vbuarque** [comment]
Finalizando dia 16/09 - Horas trabalhadas: 8 horas no total

13/09 - 2
14/09 - 2
15/09 - 2
16/09 - 2
